# Generated by Django 3.2.3 on 2021-06-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Edad Cliente'),
        ),
    ]
